apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-helm-desafio-gustavo.fullname" . }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
